apiVersion: v1     # define a versão da API
kind: Secret      # foi criado um doc tipo secret, usado para dados sensíveis.

metadata:
  name: db-secrets  #define nome do documento, será desse modo que os outros arquivos vão fazer referència a ele
type: Opaque   # Define o "formato" do Secret. que significa "genérico"

data:   # Os valores reais (Usuário e senha), um por chave. Tudo dentro de data: precisa estar em base64, exigencia do KB, mas nao garante segurança dos dados
  POSTGRES_USER: YWRtaW4=          
  POSTGRES_PASSWORD: YWRtaW5wYXNzd29yZA== 
