apiVersion: v1  #versao da API
kind: ConfigMap    #tipo do arquivo (dados de configuração não sensíveis)

metadata:
  name: api-config   #Nome de identificação do ConfigMap, q será referenciado depois em 05-api.yaml via configMapRef

data:   #Pares chave-valor em texto puro (sem base64, diferente do Secret)
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "meubanco"
  API_PORT: "8080"
  ENVIRONMENT: "production"
