apiVersion: v1  
kind: PersistentVolume
metadata:
  name: postgres-pv
#foi criado o recurso de armazenamento físico, chamado postgres-pv

spec:
  capacity:
    storage: 10Gi   #deefine a capacidade total desse volume: 10Gb
  accessModes:
    - ReadWriteOnce   #Define como o volume pode ser montado. RWO significa que apenas um nó do cluster pode montar esse volume para leitura/escrita por vez — modo típico para bancos de dados
  hostPath:
    path: "/mnt/data/postgres"   #define onde os dados serão gravados fisicamente(uma pasta no disco do proprio nó)
---     #separador indicando que abaixo começa um segundo objeto
apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: postgres-pvc
# foi criada a "solicitação" de armazenamento chamada postgres-pvc

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
    # o Pod pediu 10Gi com acesso ao RWO
